import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./common/components/organism/Header/Header";
import NextTopLoader from "nextjs-toploader";
import { ToastContainer } from "react-toastify";
import SideBar from "./common/components/organism/SideBar/SideBar";
import StoreProvider from "./(modules)/core/infrastructure/provider";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NextTopLoader
					color="#2299DD"
					initialPosition={0.08}
					crawlSpeed={200}
					height={3}
					crawl={true}
					showSpinner={true}
					easing="ease"
					speed={200}
					shadow="0 0 10px #2299DD,0 0 5px #2299DD"
				/>
				<ToastContainer />
				<StoreProvider>
					<Header />
					<div className="flex item-center p-[1rem]">
						<SideBar />
						<div className="px-[2rem] w-[100%]">{children}</div>
					</div>
				</StoreProvider>
			</body>
		</html>
	);
}
